### ISSUE TITLE
SEV-ES support

### ISSUE THREAD

**Issue by dingelish** [IBM/sev-snp-measure#1]
Hi there,

The tool looks very promising. I learnt a lot details about qemu and sev. Thank you very much! Currently I only have SEV-ES platform, and hope I could use this tool to measure SEV-ES vm. Occassionally I ran into [this thread](https://www.mail-archive.com/qemu-devel@nongnu.org/msg881274.html) and I guess that this tool is the closest tool for SEV-ES measurement. How do you think? Thanks!

**Comment by dubek** [comment]
Hi @dingelish , my plan is to add SEV and SEV-ES measurement calculation as well to this repo (probably with a `--mode sev-es` switch or something like that). I hope I can add that this month.

**Comment by dingelish** [comment]
Thanks @dubek ! Looking forward to it!

**Comment by dubek** [comment]
I added preliminary SEV and SEV-ES support in `main` (use `--mode=seves`).

I need to do some more testing and then I'll craft a proper release (later this week, I hope).
