### ISSUE TITLE
Provide Warning when OVMF is missing functionality for desired measurements.

### ISSUE THREAD

**Issue by larrydewey** [IBM/sev-snp-measure#19]
When passing command line parameters for `sev-snp-measure`, if OVMF is missing functionality for the fields specified, it would be nice to provide a warning about them not being included in the produced measurement. For example, if a user requests the cmdline to be included, but OVMF doesn't have support to include that in the measurement.

**Comment by dubek** [comment]
Good idea. I'll add it.

Also, currently sev-snp-measure silently ignores `--initrd` and `--cmdline` if `--kernel` is not specified; it would be helpful to stop and explain that `--kernel` is mandatory if one wants to specify `--initrd` and/or `--cmdline`.
