### ISSUE TITLE
Platforms >= Rome should be generating a SHA-384 instead of SHA-256

### ISSUE THREAD

**Issue by larrydewey** [IBM/sev-snp-measure#5]
Currently, regardless of the family specified, the tool always creates a SHA-256 digest. It would be beneficial to adjust this behavior to create SHA-384 digests for anything Rome or newer.

**Comment by dubek** [comment]
Thanks for the comment @larrydewey .

When launching SEV or SEV-ES guests (`--mode sev` or `--mode seves`), the computed launch digest is SHA-256, no matter if the host CPU is Naples or Rome or Milan.

For SNP guests (`--mode snp`), which require host Milan CPU, the tool uses a rolling SHA-384 as can be seen in the `GCTX` class:

https://github.com/IBM/sev-snp-measure/blob/86dbab6fff24962d29ff2b6f287126c31981ac31/sevsnpmeasure/gctx.py#L63

Do you believe this behaviour should be modified?

**Comment by larrydewey** [comment]
Thanks for responding so quickly @dubek. I double checked, and I was mistaken. Legacy SEV and SEV-ES should only be using SHA-256. SNP uses SHA-384, like you mentioned. Please disregard :slightly_smiling_face:
